# Python Basics with Numpy

In [1]:
test = "Hello World"
print("test : " + test)

test : Hello World


In [2]:
# GRADED FUNCTION : basic_sigmoid

import math

def basic_sigmoid(x):
  """
  Compute sigmoid of x.

  Arguments :
  x -- A scalar

  Return :
  s -- sigmoid(x)
  """

  s = (1/(1 + math.exp(-x)))
  return s

In [3]:
basic_sigmoid(3)

0.9525741268224334

In [4]:
basic_sigmoid(1)

0.7310585786300049

In [5]:
x = [1 , 2 , 3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [6]:
# In fact , if x = (x1 , x2 , ... , xn) is a row vector then np.exp(x) will apply the exponential function to every element of x . The output will thus be : np.exp(x) = (e^x1 , e^x2 , e^x3)

In [7]:
import numpy as np

x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [8]:
x = 1
print(np.exp(x))

2.718281828459045


In [9]:
x = np.array([1,2,3])
print(x + 3)

[4 5 6]


In [10]:
# GRADED FUNCTION : sigmoid

def sigmoid(x):
  s = 1/(np.exp(-x)  + 1)
  return s

In [11]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [12]:
# GRADED FUNCTION : sigmoid_derivative

def sigmoid_derivative(x):
  s = sigmoid(x)
  ds = s*(1-s)
  return ds

In [13]:
x = np.array([1,2,3])
print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


In [14]:
# GRADED FUNCTION : image2vector

def image2vector(image):
  v = image.reshape(image.shape[0]* image.shape[1]* image.shape[2],1)
  return v

In [16]:
image = np.array([[[0.67826139 , 0.29380381],[0.90714982 , 0.52835647],[0.4215251 ,  0.45017551]],[[0.92814219,  0.96677647],[0.85304703,  0.52351845],[0.19981397,  0.27417313]],[[0.60659855,  0.00533165],[0.10820313,  0.49978937],[0.34144279,  0.94630077]]])

print("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


## Normalizing

In [17]:
# Gradient descent converges faster after normalization which leads to better performance.

In [18]:
# By normalization we mean changin x to x/||x|| (dividing each row vector of x by its norm).

In [19]:
# GRADED FUNCTION : normalizeRows

def normalizeRows(x):
  x_norm = np.linalg.norm(x , axis = 1 , keepdims = True)
  x = x/x_norm
  return x

In [20]:
x = np.array([[0,3,4] , [1,6,4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


## Broadcasting and the softmax function

In [23]:
# GRADED FUNCTION : softmax

def softmax(x):
  x_exp = np.exp(x)
  x_sum = np.sum(x_exp , axis = 1 , keepdims = True)
  s = x_exp/x_sum
  return s

In [24]:
x = np.array([[9,2,5,0,0],[7,5,0,0,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
